### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by bbelderbos** [BenGriffith/book-api#47]
Let's try this: https://fastapi.tiangolo.com/deployment/deta/

**Comment by BenGriffith** [comment]
I was able to get the domain mapping to work so I didn't go the route of deta. If it falls apart for some reason, I'll move forward with deta. Here's link for Swagger: https://yourbooks.bengriffith.dev/docs.

**Comment by bbelderbos** [comment]
Awesome, nice you got your domain in there :)

Next your tech blog @ https://bengriffith.dev ? - GitHub pages right?

**Comment by BenGriffith** [comment]
Thanks! That's right - tech blog is next and I am still planning on using GitHub pages. Think I'm going to target end of March for when I start working on tech blog. Want to take a break from all the site stuff for a couple weeks.

**Comment by bbelderbos** [comment]
Awesome, keep going. Already have a topic / wishlist what to write about? I guess your projects have given you quite a few things :)

**Comment by BenGriffith** [comment]
Thanks Bob. Nothing specific as of yet but thinking I'll probably start with project work along with mindset.
